### ISSUE TITLE
How to use with multi-input forms?

### ISSUE THREAD

**Issue by mainrs** [crishellco/vuelidate--form-group#2]
From what I could find on the net, I find your solution to be the cleanest to use. I was wondering on how I would use it with forms that contain multiple input elements, for example to text fields. As far as I can tell (I am not that familiar with the HTML world :) ), I'd have to wrap each pair of `label` and `input` into a separate `form-group`.

Is that correct? Maybe you stumbled or created a solution for multi-input forms :)
Happy new year! 🎉

**Comment by crishellco** [comment]
Hey @SirWindfield,

It's simple! Just wrap each form element in a `<form-group />` component.

```
<template>
  <section>
    <form-group :validations="$v.name">
      <div slot-scope="{ errors, invalid }">
        <div>
          <input v-model="$v.name.$model" type="text" :class="{ invalid }" placeholder="Full name">
        </div>
        <span v-for="error in errors" class="error">{{ error }}</span>
      </div>
    </form-group>

    <form-group :validations="$v.email">
      <div slot-scope="{ errors, invalid }">
        <div>
          <input v-model="$v.email.$model" type="email" :class="{ invalid }" placeholder="Email">
        </div>
        <span v-for="error in errors" class="error">{{ error }}</span>
      </div>
    </form-group>
  </section>
</template>
```

**Comment by mainrs** [comment]
Thanks for taking your time to answer!
